using System.Collections.Generic;

namespace SystemPlus
{
    /// <summary>
    /// Provides a list of all countries with the ISO 3166 code
    /// </summary>
    public class CountryModel
    {
        /// <summary>
        /// ISO 3166 code
        /// </summary>
        public string Code { get; private set; }

        /// <summary>
        /// Country name
        /// </summary>
        public string Name { get; private set; }

        public override string ToString()
        {
            return string.Format("Id: {0}, Name: {1}", Code, Name);
        }

        public static IEnumerable<CountryModel> GetCountries()
        {
            // regex to match 'SL  Sierra Leone'
            // ^([a-z][a-z]) ([^\r\n]*)
            // new CountryModel() { Name = "$2", Code = "$1", },

            List<CountryModel> countryModels = new List<CountryModel>()
            {
                new CountryModel() { Name = "Afghanistan", Code = "AF", },
                new CountryModel() { Name = "Albania", Code = "AL", },
new CountryModel() { Name = "Algeria", Code = "DZ", },
new CountryModel() { Name = "Andorra", Code = "AD", },
new CountryModel() { Name = "Angola", Code = "AO", },
new CountryModel() { Name = "Antigua and Barbuda", Code = "AG", },
new CountryModel() { Name = "Argentina", Code = "AR", },
new CountryModel() { Name = "Armenia", Code = "AM", },
new CountryModel() { Name = "Australia", Code = "AU", },
new CountryModel() { Name = "Austria", Code = "AT", },
new CountryModel() { Name = "Azerbaijan", Code = "AZ", },
new CountryModel() { Name = "Bahamas", Code = "BS", },
new CountryModel() { Name = "Bahrain", Code = "BH", },
new CountryModel() { Name = "Bangladesh", Code = "BD", },
new CountryModel() { Name = "Barbados", Code = "BB", },
new CountryModel() { Name = "Belarus", Code = "BY", },
new CountryModel() { Name = "Belgium", Code = "BE", },
new CountryModel() { Name = "Belize", Code = "BZ", },
new CountryModel() { Name = "Benin", Code = "BJ", },
new CountryModel() { Name = "Bhutan", Code = "BT", },
new CountryModel() { Name = "Bolivia", Code = "BO", },
new CountryModel() { Name = "Bosnia and Herzegovina", Code = "BA", },
new CountryModel() { Name = "Botswana", Code = "BW", },
new CountryModel() { Name = "Brazil", Code = "BR", },
new CountryModel() { Name = "Brunei Darussalam", Code = "BN", },
new CountryModel() { Name = "Bulgaria", Code = "BG", },
new CountryModel() { Name = "Burkina Faso", Code = "BF", },
new CountryModel() { Name = "Burundi", Code = "BI", },
new CountryModel() { Name = "Cambodia", Code = "KH", },
new CountryModel() { Name = "Cameroon", Code = "CM", },
new CountryModel() { Name = "Canada", Code = "CA", },
new CountryModel() { Name = "Cape Verde", Code = "CV", },
new CountryModel() { Name = "Central African Republic", Code = "CF", },
new CountryModel() { Name = "Chad", Code = "TD", },
new CountryModel() { Name = "Chile", Code = "CL", },
new CountryModel() { Name = "China", Code = "CN", },
new CountryModel() { Name = "Colombia", Code = "CO", },
new CountryModel() { Name = "Comoros", Code = "KM", },
new CountryModel() { Name = "Congo", Code = "CG", },
new CountryModel() { Name = "Costa Rica", Code = "CR", },
new CountryModel() { Name = "Côte d'Ivoire", Code = "CI", },
new CountryModel() { Name = "Croatia", Code = "HR", },
new CountryModel() { Name = "Cuba", Code = "CU", },
new CountryModel() { Name = "Cyprus", Code = "CY", },
new CountryModel() { Name = "Czech Republic", Code = "CZ", },
new CountryModel() { Name = "Democratic People's Republic of Korea", Code = "KP", },
new CountryModel() { Name = "Democratic Republic of the Congo", Code = "CD", },
new CountryModel() { Name = "Denmark", Code = "DK", },
new CountryModel() { Name = "Djibouti", Code = "DJ", },
new CountryModel() { Name = "Dominica", Code = "DM", },
new CountryModel() { Name = "Dominican Republic", Code = "DO", },
new CountryModel() { Name = "Ecuador", Code = "EC", },
new CountryModel() { Name = "Egypt", Code = "EG", },
new CountryModel() { Name = "El Salvador", Code = "SV", },
new CountryModel() { Name = "Equatorial Guinea", Code = "GQ", },
new CountryModel() { Name = "Eritrea", Code = "ER", },
new CountryModel() { Name = "Estonia", Code = "EE", },
new CountryModel() { Name = "Ethiopia", Code = "ET", },
new CountryModel() { Name = "Fiji", Code = "FJ", },
new CountryModel() { Name = "Finland", Code = "FI", },
new CountryModel() { Name = "France", Code = "FR", },
new CountryModel() { Name = "Gabon", Code = "GA", },
new CountryModel() { Name = "Gambia", Code = "GM", },
new CountryModel() { Name = "Georgia", Code = "GE", },
new CountryModel() { Name = "Germany", Code = "DE", },
new CountryModel() { Name = "Ghana", Code = "GH", },
new CountryModel() { Name = "Greece", Code = "GR", },
new CountryModel() { Name = "Grenada", Code = "GD", },
new CountryModel() { Name = "Guatemala", Code = "GT", },
new CountryModel() { Name = "Guinea", Code = "GN", },
new CountryModel() { Name = "Guinea-Bissau", Code = "GW", },
new CountryModel() { Name = "Guyana", Code = "GY", },
new CountryModel() { Name = "Haiti", Code = "HT", },
new CountryModel() { Name = "Honduras", Code = "HN", },
new CountryModel() { Name = "Hungary", Code = "HU", },
new CountryModel() { Name = "Iceland", Code = "IS", },
new CountryModel() { Name = "India", Code = "IN", },
new CountryModel() { Name = "Indonesia", Code = "ID", },
new CountryModel() { Name = "Iran", Code = "IR", },
new CountryModel() { Name = "Iraq", Code = "IQ", },
new CountryModel() { Name = "Ireland", Code = "IE", },
new CountryModel() { Name = "Israel", Code = "IL", },
new CountryModel() { Name = "Italy", Code = "IT", },
new CountryModel() { Name = "Jamaica", Code = "JM", },
new CountryModel() { Name = "Japan", Code = "JP", },
new CountryModel() { Name = "Jordan", Code = "JO", },
new CountryModel() { Name = "Kazakhstan", Code = "KZ", },
new CountryModel() { Name = "Kenya", Code = "KE", },
new CountryModel() { Name = "Kiribati", Code = "KI", },
new CountryModel() { Name = "Kuwait", Code = "KW", },
new CountryModel() { Name = "Kyrgyzstan", Code = "KG", },
new CountryModel() { Name = "Lao People's Democratic Republic", Code = "LA", },
new CountryModel() { Name = "Latvia", Code = "LV", },
new CountryModel() { Name = "Lebanon", Code = "LB", },
new CountryModel() { Name = "Lesotho", Code = "LS", },
new CountryModel() { Name = "Liberia", Code = "LR", },
new CountryModel() { Name = "Libyan Arab Jamahiriya", Code = "LY", },
new CountryModel() { Name = "Liechtenstein", Code = "LI", },
new CountryModel() { Name = "Lithuania", Code = "LT", },
new CountryModel() { Name = "Luxembourg", Code = "LU", },
new CountryModel() { Name = "Macedonia", Code = "MK", },
new CountryModel() { Name = "Madagascar", Code = "MG", },
new CountryModel() { Name = "Malawi", Code = "MW", },
new CountryModel() { Name = "Malaysia", Code = "MY", },
new CountryModel() { Name = "Maldives", Code = "MV", },
new CountryModel() { Name = "Mali", Code = "ML", },
new CountryModel() { Name = "Malta", Code = "MT", },
new CountryModel() { Name = "Marshall Islands", Code = "MH", },
new CountryModel() { Name = "Mauritania", Code = "MR", },
new CountryModel() { Name = "Mauritius", Code = "MU", },
new CountryModel() { Name = "Mexico", Code = "MX", },
new CountryModel() { Name = "Micronesia", Code = "FM", },
new CountryModel() { Name = "Monaco", Code = "MC", },
new CountryModel() { Name = "Mongolia", Code = "MN", },
new CountryModel() { Name = "Montenegro", Code = "ME", },
new CountryModel() { Name = "Morocco", Code = "MA", },
new CountryModel() { Name = "Mozambique", Code = "MZ", },
new CountryModel() { Name = "Myanmar", Code = "MM", },
new CountryModel() { Name = "Namibia", Code = "NA", },
new CountryModel() { Name = "Nauru", Code = "NR", },
new CountryModel() { Name = "Nepal", Code = "NP", },
new CountryModel() { Name = "Netherlands", Code = "NL", },
new CountryModel() { Name = "New Zealand", Code = "NZ", },
new CountryModel() { Name = "Nicaragua", Code = "NI", },
new CountryModel() { Name = "Niger", Code = "NE", },
new CountryModel() { Name = "Nigeria", Code = "NG", },
new CountryModel() { Name = "Norway", Code = "NO", },
new CountryModel() { Name = "Oman", Code = "OM", },
new CountryModel() { Name = "Pakistan", Code = "PK", },
new CountryModel() { Name = "Palau", Code = "PW", },
new CountryModel() { Name = "Panama", Code = "PA", },
new CountryModel() { Name = "Papua New Guinea", Code = "PG", },
new CountryModel() { Name = "Paraguay", Code = "PY", },
new CountryModel() { Name = "Peru", Code = "PE", },
new CountryModel() { Name = "Philippines", Code = "PH", },
new CountryModel() { Name = "Poland", Code = "PL", },
new CountryModel() { Name = "Portugal", Code = "PT", },
new CountryModel() { Name = "Qatar", Code = "QA", },
new CountryModel() { Name = "Republic of Korea", Code = "KR", },
new CountryModel() { Name = "Republic of Moldova", Code = "MD", },
new CountryModel() { Name = "Romania", Code = "RO", },
new CountryModel() { Name = "Russia", Code = "RU", },
new CountryModel() { Name = "Rwanda", Code = "RW", },
new CountryModel() { Name = "Saint Kitts and Nevis", Code = "KN", },
new CountryModel() { Name = "Saint Lucia", Code = "LC", },
new CountryModel() { Name = "Saint Vincent and the Grenadines", Code = "VC", },
new CountryModel() { Name = "Samoa", Code = "WS", },
new CountryModel() { Name = "San Marino", Code = "SM", },
new CountryModel() { Name = "Sao Tome and Principe", Code = "ST", },
new CountryModel() { Name = "Saudi Arabia", Code = "SA", },
new CountryModel() { Name = "Senegal", Code = "SN", },
new CountryModel() { Name = "Serbia", Code = "RS", },
new CountryModel() { Name = "Seychelles", Code = "SC", },
new CountryModel() { Name = "Sierra Leone", Code = "SL", },
new CountryModel() { Name = "Singapore", Code = "SG", },
new CountryModel() { Name = "Slovakia", Code = "SK", },
new CountryModel() { Name = "Slovenia", Code = "SI", },
new CountryModel() { Name = "Solomon Islands", Code = "SB", },
new CountryModel() { Name = "Somalia", Code = "SO", },
new CountryModel() { Name = "South Africa", Code = "ZA", },
new CountryModel() { Name = "South Sudan", Code = "SS", },
new CountryModel() { Name = "Spain", Code = "ES", },
new CountryModel() { Name = "Sri Lanka", Code = "LK", },
new CountryModel() { Name = "Sudan", Code = "SD", },
new CountryModel() { Name = "Suriname", Code = "SR", },
new CountryModel() { Name = "Swaziland", Code = "SZ", },
new CountryModel() { Name = "Sweden", Code = "SE", },
new CountryModel() { Name = "Switzerland", Code = "CH", },
new CountryModel() { Name = "Syrian Arab Republic", Code = "SY", },
new CountryModel() { Name = "Tajikistan", Code = "TJ", },
new CountryModel() { Name = "Tanzania", Code = "TZ", },
new CountryModel() { Name = "Thailand", Code = "TH", },
new CountryModel() { Name = "Timor-Leste", Code = "TL", },
new CountryModel() { Name = "Togo", Code = "TG", },
new CountryModel() { Name = "Tonga", Code = "TO", },
new CountryModel() { Name = "Trinidad and Tobago", Code = "TT", },
new CountryModel() { Name = "Tunisia", Code = "TN", },
new CountryModel() { Name = "Turkey", Code = "TR", },
new CountryModel() { Name = "Turkmenistan", Code = "TM", },
new CountryModel() { Name = "Tuvalu", Code = "TV", },
new CountryModel() { Name = "Uganda", Code = "UG", },
new CountryModel() { Name = "Ukraine", Code = "UA", },
new CountryModel() { Name = "United Arab Emirates", Code = "AE", },
new CountryModel() { Name = "United Kingdom", Code = "GB", },
new CountryModel() { Name = "United States of America", Code = "US", },
new CountryModel() { Name = "Uruguay", Code = "UY", },
new CountryModel() { Name = "Uzbekistan", Code = "UZ", },
new CountryModel() { Name = "Vanuatu", Code = "VU", },
new CountryModel() { Name = "Venezuela", Code = "VE", },
new CountryModel() { Name = "Viet Nam", Code = "VN", },
new CountryModel() { Name = "Yemen", Code = "YE", },
new CountryModel() { Name = "Zambia", Code = "ZM", },
new CountryModel() { Name = "Zimbabwe", Code = "ZW", },
            };

            return countryModels;
        }
    }
}